### PR TITLE
Cleaned up the code...

### PR DESCRIPTION
**Pull request by Vaivez66**

### CODE REVIEW

**Comment by dragonwocky** [comment]
Um, why did you remove the config use statement? Don't I need that for the config section in onEnable()...?

**Comment by Ad5001** [comment]
No because I changed it (just look  at the last pull request I made ;)

**Comment by dragonwocky** [comment]
Oh ok

**Comment by Vaivez66** [comment]
You don't need to use Config statement, since you used $this->getConfig() directly

**Comment by dragonwocky** [comment]
Oh ok

**Comment by dragonwocky** [comment]
Cool xD

**Pull request merged**
