### PR TITLE
Based in Official PHP references....

### PR DESCRIPTION
**Pull request by iksaku**

### CODE REVIEW

**Comment by Taki21** [comment]
Sorry...There were some issues with Travis xD

**Comment by dragonwocky** [comment]
Thanks @iksaku! I am currently busy with the website and TeamSorter, but will probably start work on this again within a week.

**Comment by iksaku** [comment]
To prevent your `broken` Travis to mark pulls as `failed`, just disable its build in your travis dashboard, that will stop it from showing everything as errors :wink:

**Comment by dragonwocky** [comment]
😉 Good idea. I'm not sure why I even enabled it in the first place... It kept sending me error emails

**Comment by Taki21** [comment]
LOL

**Pull request merged**
